# Generated by Django 3.2.3 on 2021-06-01 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsanaUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_status', models.CharField(choices=[('need sync', 'Object changed, synchronization required'), ('synced', 'Synchronized')], default='need sync', max_length=11, verbose_name='Synchronization status')),
                ('gid', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='gid')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Asana user',
                'verbose_name_plural': 'Asana users',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_status', models.CharField(choices=[('need sync', 'Object changed, synchronization required'), ('synced', 'Synchronized')], default='need sync', max_length=11, verbose_name='Synchronization status')),
                ('gid', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='gid')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_status', models.CharField(choices=[('need sync', 'Object changed, synchronization required'), ('synced', 'Synchronized')], default='need sync', max_length=11, verbose_name='Synchronization status')),
                ('gid', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='gid')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Рабочая область',
                'verbose_name_plural': 'Рабочие области',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_status', models.CharField(choices=[('need sync', 'Object changed, synchronization required'), ('synced', 'Synchronized')], default='need sync', max_length=11, verbose_name='Synchronization status')),
                ('gid', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='gid')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='содержание')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='asana_crm.asanauser')),
                ('projects', models.ManyToManyField(blank=True, related_name='tasks', to='asana_crm.Project')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='asana_crm.workspace')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='asana_crm.workspace'),
        ),
    ]
