# Generated by Django 2.2.12 on 2020-05-27 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsanaUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_status', models.CharField(choices=[('need sync', 'Объект изменён, требуется синхронизация'), ('synced', 'Синхронизирован')], default='need sync', max_length=11, verbose_name='Статус синхронизации')),
                ('gid', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='gid')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Пользователь Asana',
                'verbose_name_plural': 'Пользователи Asana',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_status', models.CharField(choices=[('need sync', 'Объект изменён, требуется синхронизация'), ('synced', 'Синхронизирован')], default='need sync', max_length=11, verbose_name='Статус синхронизации')),
                ('gid', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='gid')),
                ('name', models.CharField(max_length=255, verbose_name='наименование')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_status', models.CharField(choices=[('need sync', 'Объект изменён, требуется синхронизация'), ('synced', 'Синхронизирован')], default='need sync', max_length=11, verbose_name='Статус синхронизации')),
                ('gid', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='gid')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Рабочая область',
                'verbose_name_plural': 'Рабочие области',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_status', models.CharField(choices=[('need sync', 'Объект изменён, требуется синхронизация'), ('synced', 'Синхронизирован')], default='need sync', max_length=11, verbose_name='Статус синхронизации')),
                ('gid', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='gid')),
                ('name', models.CharField(max_length=255, verbose_name='наименование')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='содержание')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='asana_crm.AsanaUser')),
                ('projects', models.ManyToManyField(blank=True, related_name='tasks', to='asana_crm.Project')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='asana_crm.Workspace')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='asana_crm.Workspace'),
        ),
    ]
