version: "3.7"

services:
    database:
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

    django:
        command: /app/start-django-dev.sh
        volumes:
            - "./backend/:/app/src/"
        ports:
            - "8100:8100"

    service:
        volumes:
            - "./backend/:/app/src/"
        depends_on:
            - database

    rabbitmq:
        ports:
            - "5672:5672"
            - "15672:15672"

    celery-worker:
        volumes:
            - "./backend:/app/src"

    celery-beat:
        volumes:
            - "./backend:/app/src"

volumes:
    pgdata:
